In [1]:
import numpy as np#จัดการตัวเลขarray
import pandas as pd
import yfinance
from matplotlib import pyplot as plt
import talib
import pandas_datareader as web
import datetime
from datetime import datetime
from datetime import timedelta

In [2]:
x = pd.read_excel('stocksun.xlsm')

In [3]:
freefloat = 35
valuek = 5000
netprofit=0
set_ema0=20
set_ema1=50
set_ema2=200
set_rsi=58

In [4]:
#check freefloat

In [5]:
number=x.shape[0]
number

762

In [6]:
i=0
e=0
while e< number:
    y=x.iloc[i,18]
    if y<=freefloat :
         i+=1
         e+=1
    else : 
         x = x.drop(e,axis=0)
         x.reset_index(drop=True) # Reset index
         e+=1   
print("finish")

finish

In [7]:
x.to_csv('freefloat_scan.csv')
x

,Name,No.,Links,Sign,Last,Chg%,Volume,Value (k),MCap (M),P/E,...,FFloat%,MG%,Magic1,Magic2,PEG,CG,rsi,Ema20,Ema50,Ema200
2,3K-BAT,2.0,i,NaN,67.50,0.00,0.0,0.0,5292.0,198.86,...,2.10,NaN,999.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,A,4.0,i | 1 | 2 | 3,NaN,4.98,0.00,2500.0,12.0,4880.0,30.79,...,25.86,NaN,784.0,779.0,-0.12,NaN,NaN,NaN,NaN,NaN
5,A5,5.0,i | 1 | 3,SPNC,1.50,0.00,0.0,0.0,1685.0,NaN,...,20.60,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,ABICO,7.0,i | 1 | 2 | 3,NaN,5.15,-1.90,56100.0,286.0,1259.0,28.48,...,27.66,NaN,765.0,760.0,-0.27,NaN,NaN,NaN,NaN,NaN
8,ABM,8.0,i | 1 | 3,NaN,1.43,-4.03,1616000.0,2332.0,429.0,48.96,...,34.68,NaN,936.0,927.0,-0.26,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
753,WPH,753.0,i | 1 | 2 | 3,NaN,2.14,-6.96,1332000.0,2923.0,1284.0,NaN,...,29.57,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
754,WR,754.0,i | 1 | 3,NaN,0.35,0.00,0.0,0.0,872.0,NaN,...,2.96,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
758,YGG,758.0,i | 1 | 3,NaN,20.70,-1.43,481700.0,9971.0,3726.0,63.05,...,26.32,NaN,627.0,555.0,3.86,NaN,NaN,NaN,NaN,NaN
759,YUASA,759.0,i | 1 | 3,NaN,17.30,-1.70,95800.0,1663.0,1862.0,11.53,...,15.27,NaN,225.0,177.0,0.30,NaN,NaN,NaN,NaN,NaN
760,ZEN,760.0,i | 1 | 3,NaN,11.50,-1.71,92600.0,1060.0,3450.0,381.98,...,26.68,NaN,1068.0,1081.0,-4.15,NaN,NaN,NaN,NaN,NaN

In [8]:
#check value(k)

In [9]:
a=pd.read_csv('freefloat_scan.csv')
x=a.iloc[0:,1:]

In [10]:
number=x.shape[0]
number

335

In [11]:
 y=x.iloc[0,7]
y

0.0

In [12]:
i=0
e=0
while e< number:
    y=x.iloc[i,7]
    if y > valuek :
         i+=1
         e+=1
    else : 
         x = x.drop(e,axis=0)
         x.reset_index(drop=True) # Reset index
         e+=1   
print("finish")

finish

In [13]:
x.to_csv('value_scan.csv')
x

,Name,No.,Links,Sign,Last,Chg%,Volume,Value (k),MCap (M),P/E,...,FFloat%,MG%,Magic1,Magic2,PEG,CG,rsi,Ema20,Ema50,Ema200
5,ACE,11.0,i | 1 | 3,NaN,3.92,0.00,93454200.0,365854.0,39890.0,31.30,...,22.62,NaN,600.0,555.0,0.37,NaN,NaN,NaN,NaN,NaN
7,AEC,16.0,i | 1 | 3,C,7.85,-1.26,3129900.0,24535.0,11274.0,NaN,...,25.59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,AEONTS,17.0,i | 1 | 2 | 3,NaN,186.00,-1.33,1237400.0,231962.0,46500.0,10.79,...,30.86,NaN,142.0,298.0,1.25,NaN,NaN,NaN,NaN,NaN
10,AIE,24.0,i | 1 | 2 | 3,NaN,1.33,-3.62,18802000.0,25246.0,6959.0,14.90,...,26.00,NaN,264.0,230.0,-0.10,NaN,NaN,NaN,NaN,NaN
12,ALL,31.0,i | 1 | 3,NaN,3.14,1.95,22535100.0,69730.0,2109.0,37.01,...,27.52,NaN,891.0,833.0,-12.74,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
323,VPO,738.0,i | 1 | 3,NaN,1.22,-3.17,4254600.0,5238.0,1147.0,339.16,...,32.22,NaN,1066.0,1018.0,-21.88,NaN,NaN,NaN,NaN,NaN
327,WHAUP,745.0,i | 1 | 2 | 3,NaN,4.28,-1.38,4389500.0,18954.0,16371.0,18.19,...,25.59,NaN,578.0,605.0,0.19,NaN,NaN,NaN,NaN,NaN
328,WIN,748.0,i | 1 | 2 | 3,NaN,0.85,0.00,27581700.0,23456.0,477.0,NaN,...,31.53,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
329,WINMED,749.0,i,NaN,6.90,0.00,15266300.0,104544.0,0.0,NaN,...,28.83,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
332,YGG,758.0,i | 1 | 3,NaN,20.70,-1.43,481700.0,9971.0,3726.0,63.05,...,26.32,NaN,627.0,555.0,3.86,NaN,NaN,NaN,NaN,NaN

In [14]:
#netprofit

In [15]:
a = pd.read_csv('value_scan.csv')

In [16]:
x=a.iloc[0:,1:]

In [17]:
x

,Name,No.,Links,Sign,Last,Chg%,Volume,Value (k),MCap (M),P/E,...,FFloat%,MG%,Magic1,Magic2,PEG,CG,rsi,Ema20,Ema50,Ema200
0,ACE,11.0,i | 1 | 3,NaN,3.92,0.00,93454200.0,365854.0,39890.0,31.30,...,22.62,NaN,600.0,555.0,0.37,NaN,NaN,NaN,NaN,NaN
1,AEC,16.0,i | 1 | 3,C,7.85,-1.26,3129900.0,24535.0,11274.0,NaN,...,25.59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,AEONTS,17.0,i | 1 | 2 | 3,NaN,186.00,-1.33,1237400.0,231962.0,46500.0,10.79,...,30.86,NaN,142.0,298.0,1.25,NaN,NaN,NaN,NaN,NaN
3,AIE,24.0,i | 1 | 2 | 3,NaN,1.33,-3.62,18802000.0,25246.0,6959.0,14.90,...,26.00,NaN,264.0,230.0,-0.10,NaN,NaN,NaN,NaN,NaN
4,ALL,31.0,i | 1 | 3,NaN,3.14,1.95,22535100.0,69730.0,2109.0,37.01,...,27.52,NaN,891.0,833.0,-12.74,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,VPO,738.0,i | 1 | 3,NaN,1.22,-3.17,4254600.0,5238.0,1147.0,339.16,...,32.22,NaN,1066.0,1018.0,-21.88,NaN,NaN,NaN,NaN,NaN
146,WHAUP,745.0,i | 1 | 2 | 3,NaN,4.28,-1.38,4389500.0,18954.0,16371.0,18.19,...,25.59,NaN,578.0,605.0,0.19,NaN,NaN,NaN,NaN,NaN
147,WIN,748.0,i | 1 | 2 | 3,NaN,0.85,0.00,27581700.0,23456.0,477.0,NaN,...,31.53,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148,WINMED,749.0,i,NaN,6.90,0.00,15266300.0,104544.0,0.0,NaN,...,28.83,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
149,YGG,758.0,i | 1 | 3,NaN,20.70,-1.43,481700.0,9971.0,3726.0,63.05,...,26.32,NaN,627.0,555.0,3.86,NaN,NaN,NaN,NaN,NaN

In [18]:
number=x.shape[0]
number

150

In [19]:
i=0
e=0
while e< number:
    y=x.iloc[i,16]
    if y > netprofit :
         i+=1
         e+=1
    else : 
         x = x.drop(e,axis=0)
         x.reset_index(drop=True) # Reset index
         e+=1   
print("finish")

finish

In [20]:
x.to_csv('netprofit_scan.csv')
x

,Name,No.,Links,Sign,Last,Chg%,Volume,Value (k),MCap (M),P/E,...,FFloat%,MG%,Magic1,Magic2,PEG,CG,rsi,Ema20,Ema50,Ema200
0,ACE,11.0,i | 1 | 3,NaN,3.92,0.00,93454200.0,365854.0,39890.0,31.30,...,22.62,NaN,600.0,555.0,0.37,NaN,NaN,NaN,NaN,NaN
2,AEONTS,17.0,i | 1 | 2 | 3,NaN,186.00,-1.33,1237400.0,231962.0,46500.0,10.79,...,30.86,NaN,142.0,298.0,1.25,NaN,NaN,NaN,NaN,NaN
3,AIE,24.0,i | 1 | 2 | 3,NaN,1.33,-3.62,18802000.0,25246.0,6959.0,14.90,...,26.00,NaN,264.0,230.0,-0.10,NaN,NaN,NaN,NaN,NaN
5,ALLA,32.0,i | 1 | 2 | 3,NaN,1.92,-2.54,3189000.0,6133.0,1152.0,31.30,...,34.44,NaN,798.0,766.0,21.22,NaN,NaN,NaN,NaN,NaN
8,APCO,44.0,i | 1 | 2 | 3,NaN,6.35,-2.31,1026600.0,6567.0,3810.0,61.43,...,30.79,NaN,730.0,613.0,-17.53,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
143,VNG,736.0,i | 1 | 2 | 3,NaN,7.45,-3.87,2847900.0,21417.0,12928.0,NaN,...,22.19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
144,VNT,737.0,i | 1 | 3,NaN,37.50,0.00,803500.0,30146.0,44445.0,15.98,...,16.24,NaN,414.0,311.0,0.37,NaN,NaN,NaN,NaN,NaN
146,WHAUP,745.0,i | 1 | 2 | 3,NaN,4.28,-1.38,4389500.0,18954.0,16371.0,18.19,...,25.59,NaN,578.0,605.0,0.19,NaN,NaN,NaN,NaN,NaN
148,WINMED,749.0,i,NaN,6.90,0.00,15266300.0,104544.0,0.0,NaN,...,28.83,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
149,YGG,758.0,i | 1 | 3,NaN,20.70,-1.43,481700.0,9971.0,3726.0,63.05,...,26.32,NaN,627.0,555.0,3.86,NaN,NaN,NaN,NaN,NaN

In [21]:
#check RSI

In [22]:
g=pd.read_csv('netprofit_scan.csv')#เลือกหุ้น
x=g.iloc[0:,1:]
x

,Name,No.,Links,Sign,Last,Chg%,Volume,Value (k),MCap (M),P/E,...,FFloat%,MG%,Magic1,Magic2,PEG,CG,rsi,Ema20,Ema50,Ema200
0,ACE,11.0,i | 1 | 3,NaN,3.92,0.00,93454200.0,365854.0,39890.0,31.30,...,22.62,NaN,600.0,555.0,0.37,NaN,NaN,NaN,NaN,NaN
1,AEONTS,17.0,i | 1 | 2 | 3,NaN,186.00,-1.33,1237400.0,231962.0,46500.0,10.79,...,30.86,NaN,142.0,298.0,1.25,NaN,NaN,NaN,NaN,NaN
2,AIE,24.0,i | 1 | 2 | 3,NaN,1.33,-3.62,18802000.0,25246.0,6959.0,14.90,...,26.00,NaN,264.0,230.0,-0.10,NaN,NaN,NaN,NaN,NaN
3,ALLA,32.0,i | 1 | 2 | 3,NaN,1.92,-2.54,3189000.0,6133.0,1152.0,31.30,...,34.44,NaN,798.0,766.0,21.22,NaN,NaN,NaN,NaN,NaN
4,APCO,44.0,i | 1 | 2 | 3,NaN,6.35,-2.31,1026600.0,6567.0,3810.0,61.43,...,30.79,NaN,730.0,613.0,-17.53,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
124,VNG,736.0,i | 1 | 2 | 3,NaN,7.45,-3.87,2847900.0,21417.0,12928.0,NaN,...,22.19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
125,VNT,737.0,i | 1 | 3,NaN,37.50,0.00,803500.0,30146.0,44445.0,15.98,...,16.24,NaN,414.0,311.0,0.37,NaN,NaN,NaN,NaN,NaN
126,WHAUP,745.0,i | 1 | 2 | 3,NaN,4.28,-1.38,4389500.0,18954.0,16371.0,18.19,...,25.59,NaN,578.0,605.0,0.19,NaN,NaN,NaN,NaN,NaN
127,WINMED,749.0,i,NaN,6.90,0.00,15266300.0,104544.0,0.0,NaN,...,28.83,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
128,YGG,758.0,i | 1 | 3,NaN,20.70,-1.43,481700.0,9971.0,3726.0,63.05,...,26.32,NaN,627.0,555.0,3.86,NaN,NaN,NaN,NaN,NaN

In [23]:
a=x.iloc[0:,24]
a

0     NaN
1     NaN
2     NaN
3     NaN
4     NaN
       ..
124   NaN
125   NaN
126   NaN
127   NaN
128   NaN
Name:       rsi, Length: 129, dtype: float64

In [24]:
number=x.shape[0]
y=x.iloc[0,0]
y

'ACE'

In [25]:
i=0
e=0
while e <number:
 y=x.iloc[i,0]
 from datetime import datetime
 from datetime import timedelta
 now = datetime.today()
 duration= timedelta(days=300)
 start=now-duration
 s = yfinance.download(y+".BK",start,now)
 rsi = talib.RSI(s["Close"])
 print_rsi=rsi[-1]
 stock_rsi=print_rsi
 if stock_rsi>set_rsi:
   x.iloc[i,24]=stock_rsi
   i+=1
   e+=1
 else  : 
   x = x.drop(e,axis=0)
   x.reset_index(drop=True) # Reset index
   e+=1
print("finish")

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
finish

In [26]:
x.to_csv('rsi_scan.csv')
x

,Name,No.,Links,Sign,Last,Chg%,Volume,Value (k),MCap (M),P/E,...,FFloat%,MG%,Magic1,Magic2,PEG,CG,rsi,Ema20,Ema50,Ema200
0,ACE,11.0,i | 1 | 3,NaN,3.92,0.00,93454200.0,365854.0,39890.0,31.30,...,22.62,NaN,600.0,555.0,0.37,NaN,63.469076,NaN,NaN,NaN
4,APCO,44.0,i | 1 | 2 | 3,NaN,6.35,-2.31,1026600.0,6567.0,3810.0,61.43,...,30.79,NaN,730.0,613.0,-17.53,NaN,60.372704,NaN,NaN,NaN
5,APURE,48.0,i | 1 | 2 | 3,NaN,6.20,9.73,138523700.0,869819.0,5941.0,19.25,...,26.92,NaN,385.0,318.0,0.10,NaN,85.344956,NaN,NaN,NaN
6,ARIP,52.0,i | 1 | 2 | 3,NaN,1.03,0.98,18361100.0,18393.0,480.0,135.53,...,28.67,NaN,1027.0,1036.0,10.89,NaN,64.034897,NaN,NaN,NaN
13,BGC,87.0,i | 1 | 3,NaN,11.50,-2.54,9710100.0,110476.0,7986.0,14.85,...,27.41,NaN,440.0,579.0,7.33,NaN,62.269328,NaN,NaN,NaN
14,BIZ,92.0,i | 1 | 2 | 3,NaN,9.60,-2.04,2671000.0,25625.0,3840.0,34.63,...,24.41,NaN,492.0,625.0,8.41,NaN,60.274988,NaN,NaN,NaN
18,CBG,115.0,i | 1 | 2 | 3,NaN,151.50,0.00,4514900.0,681010.0,151500.0,44.24,...,28.85,NaN,449.0,445.0,1.45,NaN,66.008683,NaN,NaN,NaN
21,CKP,135.0,i | 1 | 2 | 3,NaN,5.90,0.00,71950200.0,431845.0,47963.0,55.85,...,24.22,NaN,922.0,936.0,0.78,NaN,58.433739,NaN,NaN,NaN
32,DTAC,177.0,i | 1 | 2 | 3,NaN,31.75,2.42,17459200.0,551269.0,75178.0,18.48,...,29.26,NaN,329.0,627.0,-0.15,NaN,66.467487,NaN,NaN,NaN
35,EPG,193.0,i | 1 | 2 | 3,NaN,13.00,0.78,45757400.0,595634.0,36400.0,29.86,...,25.90,NaN,578.0,541.0,-7.51,NaN,67.128540,NaN,NaN,NaN
41,GLOBAL,225.0,i | 1 | 2 | 3,NaN,23.80,-1.24,9738600.0,231378.0,109520.0,47.50,...,32.11,NaN,623.0,653.0,2.38,NaN,65.924253,NaN,NaN,NaN
42,GPSC,228.0,i | 1 | 2 | 3,NaN,79.75,-0.62,21824900.0,1737063.0,224873.0,28.46,...,24.75,NaN,663.0,680.0,0.83,NaN,65.448270,NaN,NaN,NaN
55,LANNA,319.0,i | 1 | 2 | 3,NaN,18.40,0.55,3943900.0,72541.0,9660.0,27.54,...,24.48,NaN,665.0,537.0,1.76,NaN,59.825304,NaN,NaN,NaN
61,MTC,372.0,i | 1 | 2 | 3,NaN,63.25,-1.17,6956600.0,438791.0,134090.0,25.06,...,32.12,NaN,355.0,440.0,0.54,NaN,65.226404,NaN,NaN,NaN
63,NDR,381.0,i | 1 | 2 | 3,NaN,3.38,-3.98,12458000.0,42588.0,1141.0,19.53,...,23.09,NaN,572.0,506.0,-0.22,NaN,66.804436,NaN,NaN,NaN
65,NSL,399.0,i,NaN,15.30,-1.29,3545300.0,54049.0,0.0,NaN,...,25.00,NaN,NaN,NaN,NaN,NaN,62.995120,NaN,NaN,NaN
76,RWI,493.0,i | 1 | 3,NaN,2.04,-2.86,40685500.0,84860.0,1298.0,5.97,...,20.01,NaN,64.0,28.0,-0.06,NaN,72.332580,NaN,NaN,NaN
85,SCGP,518.0,i | 1 | 3,NaN,64.00,-0.39,5839600.0,373367.0,274747.0,40.05,...,26.21,NaN,736.0,728.0,NaN,NaN,61.317607,NaN,NaN,NaN
96,SONIC,565.0,i | 1 | 3,NaN,5.00,0.00,45384900.0,230170.0,2750.0,31.51,...,31.66,NaN,547.0,483.0,2.22,NaN,66.424291,NaN,NaN,NaN
104,SVI,601.0,i | 1 | 2 | 3,NaN,4.88,0.83,15463500.0,76477.0,10593.0,17.28,...,18.66,NaN,365.0,475.0,21.39,NaN,60.025285,NaN,NaN,NaN
113,TPLAS,676.0,i | 1 | 3,NaN,5.00,-2.91,16328300.0,83010.0,1350.0,35.21,...,25.73,NaN,598.0,496.0,1.61,NaN,66.707259,NaN,NaN,NaN
122,VIH,734.0,i | 1 | 2 | 3,NaN,12.90,-3.73,3461900.0,44662.0,7362.0,36.34,...,29.03,NaN,559.0,526.0,2.27,NaN,59.773859,NaN,NaN,NaN

In [27]:
#filter code

In [28]:
#Ema

In [29]:
a=pd.read_csv('rsi_scan.csv')#เลือกหุ้น
x=a.iloc[0:,1:]
x

,Name,No.,Links,Sign,Last,Chg%,Volume,Value (k),MCap (M),P/E,...,FFloat%,MG%,Magic1,Magic2,PEG,CG,rsi,Ema20,Ema50,Ema200
0,ACE,11.0,i | 1 | 3,NaN,3.92,0.00,93454200.0,365854.0,39890.0,31.30,...,22.62,NaN,600.0,555.0,0.37,NaN,63.469076,NaN,NaN,NaN
1,APCO,44.0,i | 1 | 2 | 3,NaN,6.35,-2.31,1026600.0,6567.0,3810.0,61.43,...,30.79,NaN,730.0,613.0,-17.53,NaN,60.372704,NaN,NaN,NaN
2,APURE,48.0,i | 1 | 2 | 3,NaN,6.20,9.73,138523700.0,869819.0,5941.0,19.25,...,26.92,NaN,385.0,318.0,0.10,NaN,85.344956,NaN,NaN,NaN
3,ARIP,52.0,i | 1 | 2 | 3,NaN,1.03,0.98,18361100.0,18393.0,480.0,135.53,...,28.67,NaN,1027.0,1036.0,10.89,NaN,64.034897,NaN,NaN,NaN
4,BGC,87.0,i | 1 | 3,NaN,11.50,-2.54,9710100.0,110476.0,7986.0,14.85,...,27.41,NaN,440.0,579.0,7.33,NaN,62.269328,NaN,NaN,NaN
5,BIZ,92.0,i | 1 | 2 | 3,NaN,9.60,-2.04,2671000.0,25625.0,3840.0,34.63,...,24.41,NaN,492.0,625.0,8.41,NaN,60.274988,NaN,NaN,NaN
6,CBG,115.0,i | 1 | 2 | 3,NaN,151.50,0.00,4514900.0,681010.0,151500.0,44.24,...,28.85,NaN,449.0,445.0,1.45,NaN,66.008683,NaN,NaN,NaN
7,CKP,135.0,i | 1 | 2 | 3,NaN,5.90,0.00,71950200.0,431845.0,47963.0,55.85,...,24.22,NaN,922.0,936.0,0.78,NaN,58.433739,NaN,NaN,NaN
8,DTAC,177.0,i | 1 | 2 | 3,NaN,31.75,2.42,17459200.0,551269.0,75178.0,18.48,...,29.26,NaN,329.0,627.0,-0.15,NaN,66.467487,NaN,NaN,NaN
9,EPG,193.0,i | 1 | 2 | 3,NaN,13.00,0.78,45757400.0,595634.0,36400.0,29.86,...,25.90,NaN,578.0,541.0,-7.51,NaN,67.128540,NaN,NaN,NaN
10,GLOBAL,225.0,i | 1 | 2 | 3,NaN,23.80,-1.24,9738600.0,231378.0,109520.0,47.50,...,32.11,NaN,623.0,653.0,2.38,NaN,65.924253,NaN,NaN,NaN
11,GPSC,228.0,i | 1 | 2 | 3,NaN,79.75,-0.62,21824900.0,1737063.0,224873.0,28.46,...,24.75,NaN,663.0,680.0,0.83,NaN,65.448270,NaN,NaN,NaN
12,LANNA,319.0,i | 1 | 2 | 3,NaN,18.40,0.55,3943900.0,72541.0,9660.0,27.54,...,24.48,NaN,665.0,537.0,1.76,NaN,59.825304,NaN,NaN,NaN
13,MTC,372.0,i | 1 | 2 | 3,NaN,63.25,-1.17,6956600.0,438791.0,134090.0,25.06,...,32.12,NaN,355.0,440.0,0.54,NaN,65.226404,NaN,NaN,NaN
14,NDR,381.0,i | 1 | 2 | 3,NaN,3.38,-3.98,12458000.0,42588.0,1141.0,19.53,...,23.09,NaN,572.0,506.0,-0.22,NaN,66.804436,NaN,NaN,NaN
15,NSL,399.0,i,NaN,15.30,-1.29,3545300.0,54049.0,0.0,NaN,...,25.00,NaN,NaN,NaN,NaN,NaN,62.995120,NaN,NaN,NaN
16,RWI,493.0,i | 1 | 3,NaN,2.04,-2.86,40685500.0,84860.0,1298.0,5.97,...,20.01,NaN,64.0,28.0,-0.06,NaN,72.332580,NaN,NaN,NaN
17,SCGP,518.0,i | 1 | 3,NaN,64.00,-0.39,5839600.0,373367.0,274747.0,40.05,...,26.21,NaN,736.0,728.0,NaN,NaN,61.317607,NaN,NaN,NaN
18,SONIC,565.0,i | 1 | 3,NaN,5.00,0.00,45384900.0,230170.0,2750.0,31.51,...,31.66,NaN,547.0,483.0,2.22,NaN,66.424291,NaN,NaN,NaN
19,SVI,601.0,i | 1 | 2 | 3,NaN,4.88,0.83,15463500.0,76477.0,10593.0,17.28,...,18.66,NaN,365.0,475.0,21.39,NaN,60.025285,NaN,NaN,NaN
20,TPLAS,676.0,i | 1 | 3,NaN,5.00,-2.91,16328300.0,83010.0,1350.0,35.21,...,25.73,NaN,598.0,496.0,1.61,NaN,66.707259,NaN,NaN,NaN
21,VIH,734.0,i | 1 | 2 | 3,NaN,12.90,-3.73,3461900.0,44662.0,7362.0,36.34,...,29.03,NaN,559.0,526.0,2.27,NaN,59.773859,NaN,NaN,NaN

In [30]:
stock_ema=x.iloc[0:,25] #first stock in ema
stock_ema

0    NaN
1    NaN
2    NaN
3    NaN
4    NaN
5    NaN
6    NaN
7    NaN
8    NaN
9    NaN
10   NaN
11   NaN
12   NaN
13   NaN
14   NaN
15   NaN
16   NaN
17   NaN
18   NaN
19   NaN
20   NaN
21   NaN
Name: Ema20, dtype: float64

In [31]:
#เทสEMA

In [32]:
 number=x.shape[0]
 y=x.iloc[0,0]
y

'ACE'

In [33]:
i=0
e=0
while e <number:
  y=x.iloc[i,0]
  end = datetime.today()
  duration= timedelta(days=365)
  start=end-duration
  s = web.DataReader(y+".BK", 'yahoo', start, end)
  close_array=s.iloc[0:,3:-2]
  close_array['EMA'] = talib.EMA(close_array['Close'], timeperiod =set_ema0)
  close_data = close_array.iloc[-1,0]
  ema_data0 =close_array.iloc[-1,1]
  stock_ema0 = ema_data0
  close_array['EMA'] = talib.EMA(close_array['Close'], timeperiod =set_ema1)
  ema_data1 =close_array.iloc[-1,1]
  stock_ema1 = ema_data1
  close_array['EMA'] = talib.EMA(close_array['Close'], timeperiod =set_ema2)
  ema_data2 =close_array.iloc[-1,1]
  stock_ema2 = ema_data2
  if close_data > stock_ema0 and close_data > stock_ema1 and close_data > stock_ema2 :
   x.iloc[i,25]=stock_ema0
   x.iloc[i,26]=stock_ema1
   x.iloc[i,27]=stock_ema2
   i+=1
   e+=1
  else  : 
   x = x.drop(e,axis=0)
   x.reset_index(drop=True) # Reset index
   e+=1
print("finish")

finish

In [34]:
x.to_csv('finish_scan.csv')
x

,Name,No.,Links,Sign,Last,Chg%,Volume,Value (k),MCap (M),P/E,...,FFloat%,MG%,Magic1,Magic2,PEG,CG,rsi,Ema20,Ema50,Ema200
0,ACE,11.0,i | 1 | 3,NaN,3.92,0.00,93454200.0,365854.0,39890.0,31.30,...,22.62,NaN,600.0,555.0,0.37,NaN,63.469076,3.833774,3.763380,3.563184
1,APCO,44.0,i | 1 | 2 | 3,NaN,6.35,-2.31,1026600.0,6567.0,3810.0,61.43,...,30.79,NaN,730.0,613.0,-17.53,NaN,60.372704,5.739427,4.941259,4.124664
2,APURE,48.0,i | 1 | 2 | 3,NaN,6.20,9.73,138523700.0,869819.0,5941.0,19.25,...,26.92,NaN,385.0,318.0,0.10,NaN,85.344956,4.881783,4.570341,3.320538
3,ARIP,52.0,i | 1 | 2 | 3,NaN,1.03,0.98,18361100.0,18393.0,480.0,135.53,...,28.67,NaN,1027.0,1036.0,10.89,NaN,64.034897,0.936660,0.833555,0.611221
4,BGC,87.0,i | 1 | 3,NaN,11.50,-2.54,9710100.0,110476.0,7986.0,14.85,...,27.41,NaN,440.0,579.0,7.33,NaN,62.269328,11.129131,10.662512,10.541135
5,BIZ,92.0,i | 1 | 2 | 3,NaN,9.60,-2.04,2671000.0,25625.0,3840.0,34.63,...,24.41,NaN,492.0,625.0,8.41,NaN,60.274988,9.075284,7.734639,5.203406
6,CBG,115.0,i | 1 | 2 | 3,NaN,151.50,0.00,4514900.0,681010.0,151500.0,44.24,...,28.85,NaN,449.0,445.0,1.45,NaN,66.008683,147.376806,139.611624,129.396565
7,CKP,135.0,i | 1 | 2 | 3,NaN,5.90,0.00,71950200.0,431845.0,47963.0,55.85,...,24.22,NaN,922.0,936.0,0.78,NaN,58.433739,5.675990,5.522283,5.180467
9,EPG,193.0,i | 1 | 2 | 3,NaN,13.00,0.78,45757400.0,595634.0,36400.0,29.86,...,25.90,NaN,578.0,541.0,-7.51,NaN,67.128540,12.236341,11.674395,8.797072
10,GLOBAL,225.0,i | 1 | 2 | 3,NaN,23.80,-1.24,9738600.0,231378.0,109520.0,47.50,...,32.11,NaN,623.0,653.0,2.38,NaN,65.924253,23.227888,22.437841,20.058883
11,GPSC,228.0,i | 1 | 2 | 3,NaN,79.75,-0.62,21824900.0,1737063.0,224873.0,28.46,...,24.75,NaN,663.0,680.0,0.83,NaN,65.448270,76.584775,75.059844,71.721049
12,LANNA,319.0,i | 1 | 2 | 3,NaN,18.40,0.55,3943900.0,72541.0,9660.0,27.54,...,24.48,NaN,665.0,537.0,1.76,NaN,59.825304,16.687715,14.760211,10.135083
13,MTC,372.0,i | 1 | 2 | 3,NaN,63.25,-1.17,6956600.0,438791.0,134090.0,25.06,...,32.12,NaN,355.0,440.0,0.54,NaN,65.226404,60.801670,60.991874,59.305440
14,NDR,381.0,i | 1 | 2 | 3,NaN,3.38,-3.98,12458000.0,42588.0,1141.0,19.53,...,23.09,NaN,572.0,506.0,-0.22,NaN,66.804436,3.153284,2.970987,2.150544
16,RWI,493.0,i | 1 | 3,NaN,2.04,-2.86,40685500.0,84860.0,1298.0,5.97,...,20.01,NaN,64.0,28.0,-0.06,NaN,72.332580,1.873661,1.760760,1.501287
18,SONIC,565.0,i | 1 | 3,NaN,5.00,0.00,45384900.0,230170.0,2750.0,31.51,...,31.66,NaN,547.0,483.0,2.22,NaN,66.424291,4.730973,4.303157,2.755853
19,SVI,601.0,i | 1 | 2 | 3,NaN,4.88,0.83,15463500.0,76477.0,10593.0,17.28,...,18.66,NaN,365.0,475.0,21.39,NaN,60.025285,4.850994,4.878854,4.671564
20,TPLAS,676.0,i | 1 | 3,NaN,5.00,-2.91,16328300.0,83010.0,1350.0,35.21,...,25.73,NaN,598.0,496.0,1.61,NaN,66.707259,4.431785,3.547633,2.298068
21,VIH,734.0,i | 1 | 2 | 3,NaN,12.90,-3.73,3461900.0,44662.0,7362.0,36.34,...,29.03,NaN,559.0,526.0,2.27,NaN,59.773859,12.525213,11.096261,8.561036