In [14]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
x = pd.read_excel('stocksun.xlsm')

In [15]:
x

,Name,No.,Links,Sign,Last,Chg%,Volume,Value (k),MCap (M),P/E,...,ROA%,ROE%,NPM%,Yield%,FFloat%,MG%,Magic1,Magic2,PEG,CG
0,Average,NaN,NaN,NaN,18.55,-1.43,1.718772e+07,122323.72,23210.49,46.38,...,4.65,3.43,-20.56,0.05,40.86,NaN,546.39,546.4,0.55,NaN
1,2S,1.0,i | 1 | 2 | 3,NaN,5.70,0.00,2.929000e+05,1662.00,2850.00,5.40,...,31.02,30.35,14.66,3.95,58.11,NaN,46.00,22.0,0.03,NaN
2,3K-BAT,2.0,i,NaN,67.50,0.00,0.000000e+00,0.00,5292.00,198.86,...,-2.57,3.20,2.79,0.35,2.10,NaN,999.00,NaN,NaN,NaN
3,7UP,3.0,i | 1 | 2 | 3,NaN,2.96,4.23,2.364791e+08,685558.00,15223.00,83.22,...,7.63,9.76,55.14,NaN,66.55,NaN,763.00,741.0,-1.06,NaN
4,A,4.0,i | 1 | 2 | 3,NaN,4.98,0.00,2.500000e+03,12.00,4880.00,30.79,...,3.85,4.58,-3.81,0.60,25.86,NaN,784.00,779.0,-0.12,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
757,YCI,757.0,i | 1 | 2 | 3,SPNC,13.20,0.00,0.000000e+00,0.00,92.00,NaN,...,-8.45,-11.25,-7.07,NaN,43.53,NaN,NaN,NaN,NaN,NaN
758,YGG,758.0,i | 1 | 3,NaN,20.70,-1.43,4.817000e+05,9971.00,3726.00,63.05,...,14.16,15.77,25.75,0.83,26.32,NaN,627.00,555.0,3.86,NaN
759,YUASA,759.0,i | 1 | 3,NaN,17.30,-1.70,9.580000e+04,1663.00,1862.00,11.53,...,14.93,18.63,7.39,2.51,15.27,NaN,225.00,177.0,0.30,NaN
760,ZEN,760.0,i | 1 | 3,NaN,11.50,-1.71,9.260000e+04,1060.00,3450.00,381.98,...,1.18,0.69,4.70,2.14,26.68,NaN,1068.00,1081.0,-4.15,NaN
761,ZIGA,761.0,i | 1 | 2 | 3,NaN,4.92,-1.60,5.785000e+06,28590.00,2446.00,17.74,...,13.48,18.22,11.23,3.22,37.17,NaN,343.00,313.0,0.36,NaN

In [16]:
number=x.shape[0]
number

762

In [17]:
freefote = 35

In [18]:
 y=x.iloc[0,18]
y

40.86

In [20]:
i=0
e=0
while e< number:
    y=x.iloc[i,18]
    if y<=freefote :
         i+=1
         e+=1
    else : 
         x = x.drop(e,axis=0)
         x.reset_index(drop=True) # Reset index
         e+=1   
print("finish")

finish

In [21]:
x.to_csv('freefote_scan.csv')
x

,Name,No.,Links,Sign,Last,Chg%,Volume,Value (k),MCap (M),P/E,...,ROA%,ROE%,NPM%,Yield%,FFloat%,MG%,Magic1,Magic2,PEG,CG
2,3K-BAT,2.0,i,NaN,67.50,0.00,0.0,0.0,5292.0,198.86,...,-2.57,3.20,2.79,0.35,2.10,NaN,999.0,NaN,NaN,NaN
4,A,4.0,i | 1 | 2 | 3,NaN,4.98,0.00,2500.0,12.0,4880.0,30.79,...,3.85,4.58,-3.81,0.60,25.86,NaN,784.0,779.0,-0.12,NaN
5,A5,5.0,i | 1 | 3,SPNC,1.50,0.00,0.0,0.0,1685.0,NaN,...,13.18,21.50,37.45,NaN,20.60,NaN,NaN,NaN,NaN,NaN
7,ABICO,7.0,i | 1 | 2 | 3,NaN,5.15,-1.90,56100.0,286.0,1259.0,28.48,...,3.92,4.75,1.52,0.08,27.66,NaN,765.0,760.0,-0.27,NaN
8,ABM,8.0,i | 1 | 3,NaN,1.43,-4.03,1616000.0,2332.0,429.0,48.96,...,2.74,2.93,1.95,NaN,34.68,NaN,936.0,927.0,-0.26,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
753,WPH,753.0,i | 1 | 2 | 3,NaN,2.14,-6.96,1332000.0,2923.0,1284.0,NaN,...,-3.11,-5.43,-8.80,1.63,29.57,NaN,NaN,NaN,NaN,NaN
754,WR,754.0,i | 1 | 3,NaN,0.35,0.00,0.0,0.0,872.0,NaN,...,-6.25,-19.37,-330.22,NaN,2.96,NaN,NaN,NaN,NaN,NaN
758,YGG,758.0,i | 1 | 3,NaN,20.70,-1.43,481700.0,9971.0,3726.0,63.05,...,14.16,15.77,25.75,0.83,26.32,NaN,627.0,555.0,3.86,NaN
759,YUASA,759.0,i | 1 | 3,NaN,17.30,-1.70,95800.0,1663.0,1862.0,11.53,...,14.93,18.63,7.39,2.51,15.27,NaN,225.0,177.0,0.30,NaN
760,ZEN,760.0,i | 1 | 3,NaN,11.50,-1.71,92600.0,1060.0,3450.0,381.98,...,1.18,0.69,4.70,2.14,26.68,NaN,1068.0,1081.0,-4.15,NaN