In [55]:

import pandas as pd
a = pd.read_csv('value_filter.csv')

In [56]:
x=a.iloc[0:,1:]
x

,Name,No.,Links,Sign,Last,Chg%,Volume,Value (k),MCap (M),P/E,...,ROA%,ROE%,NPM%,Yield%,FFloat%,MG%,Magic1,Magic2,PEG,CG
0,ACE,11.0,i | 1 | 3,NaN,3.92,0.00,93454200.0,365854.0,39890.0,31.30,...,8.80,10.74,27.38,1.22,22.62,NaN,600.0,555.0,0.37,NaN
1,AEC,16.0,i | 1 | 3,C,7.85,-1.26,3129900.0,24535.0,11274.0,NaN,...,-27.16,-44.61,-32.96,NaN,25.59,NaN,NaN,NaN,NaN,NaN
2,AEONTS,17.0,i | 1 | 2 | 3,NaN,186.00,-1.33,1237400.0,231962.0,46500.0,10.79,...,8.51,26.36,22.99,2.39,30.86,NaN,142.0,298.0,1.25,NaN
3,AIE,24.0,i | 1 | 2 | 3,NaN,1.33,-3.62,18802000.0,25246.0,6959.0,14.90,...,18.30,22.78,7.60,3.62,26.00,NaN,264.0,230.0,-0.10,NaN
4,ALL,31.0,i | 1 | 3,NaN,3.14,1.95,22535100.0,69730.0,2109.0,37.01,...,3.72,2.70,-28.05,1.35,27.52,NaN,891.0,833.0,-12.74,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144,VPO,738.0,i | 1 | 3,NaN,1.22,-3.17,4254600.0,5238.0,1147.0,339.16,...,2.53,0.68,-16.90,NaN,32.22,NaN,1066.0,1018.0,-21.88,NaN
145,WHAUP,745.0,i | 1 | 2 | 3,NaN,4.28,-1.38,4389500.0,18954.0,16371.0,18.19,...,4.98,7.24,16.96,5.82,25.59,NaN,578.0,605.0,0.19,NaN
146,WIN,748.0,i | 1 | 2 | 3,NaN,0.85,0.00,27581700.0,23456.0,477.0,NaN,...,-9.44,-31.21,-4.61,NaN,31.53,NaN,NaN,NaN,NaN,NaN
147,WINMED,749.0,i,NaN,6.90,0.00,15266300.0,104544.0,0.0,NaN,...,13.00,24.74,8.87,-,28.83,NaN,NaN,NaN,NaN,NaN
148,YGG,758.0,i | 1 | 3,NaN,20.70,-1.43,481700.0,9971.0,3726.0,63.05,...,14.16,15.77,25.75,0.83,26.32,NaN,627.0,555.0,3.86,NaN

In [57]:
netprofit=0

In [58]:
number=x.shape[0]
number

149

In [60]:
 y=x.iloc[0,16]
y

27.38

In [61]:
i=0
e=0
while e< number:
    y=x.iloc[i,16]
    if y > netprofit :
         i+=1
         e+=1
    else : 
         x = x.drop(e,axis=0)
         x.reset_index(drop=True) # Reset index
         e+=1   
print("finish")

finish

In [63]:
x.to_csv('netprofit_scan.csv')
x

,Name,No.,Links,Sign,Last,Chg%,Volume,Value (k),MCap (M),P/E,...,ROA%,ROE%,NPM%,Yield%,FFloat%,MG%,Magic1,Magic2,PEG,CG
0,ACE,11.0,i | 1 | 3,NaN,3.92,0.00,93454200.0,365854.0,39890.0,31.30,...,8.80,10.74,27.38,1.22,22.62,NaN,600.0,555.0,0.37,NaN
2,AEONTS,17.0,i | 1 | 2 | 3,NaN,186.00,-1.33,1237400.0,231962.0,46500.0,10.79,...,8.51,26.36,22.99,2.39,30.86,NaN,142.0,298.0,1.25,NaN
3,AIE,24.0,i | 1 | 2 | 3,NaN,1.33,-3.62,18802000.0,25246.0,6959.0,14.90,...,18.30,22.78,7.60,3.62,26.00,NaN,264.0,230.0,-0.10,NaN
5,ALLA,32.0,i | 1 | 2 | 3,NaN,1.92,-2.54,3189000.0,6133.0,1152.0,31.30,...,4.27,4.24,7.83,3.55,34.44,NaN,798.0,766.0,21.22,NaN
8,APCO,44.0,i | 1 | 2 | 3,NaN,6.35,-2.31,1026600.0,6567.0,3810.0,61.43,...,11.39,10.31,18.30,1.85,30.79,NaN,730.0,613.0,-17.53,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142,VNG,736.0,i | 1 | 2 | 3,NaN,7.45,-3.87,2847900.0,21417.0,12928.0,NaN,...,-0.06,-4.50,4.12,NaN,22.19,NaN,NaN,NaN,NaN,NaN
143,VNT,737.0,i | 1 | 3,NaN,37.50,0.00,803500.0,30146.0,44445.0,15.98,...,12.34,12.01,22.95,2.40,16.24,NaN,414.0,311.0,0.37,NaN
145,WHAUP,745.0,i | 1 | 2 | 3,NaN,4.28,-1.38,4389500.0,18954.0,16371.0,18.19,...,4.98,7.24,16.96,5.82,25.59,NaN,578.0,605.0,0.19,NaN
147,WINMED,749.0,i,NaN,6.90,0.00,15266300.0,104544.0,0.0,NaN,...,13.00,24.74,8.87,-,28.83,NaN,NaN,NaN,NaN,NaN
148,YGG,758.0,i | 1 | 3,NaN,20.70,-1.43,481700.0,9971.0,3726.0,63.05,...,14.16,15.77,25.75,0.83,26.32,NaN,627.0,555.0,3.86,NaN